# Generated by Django 5.0.4 on 2024-04-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_photo_alter_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
