# Generated by Django 5.0.4 on 2024-06-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinventory',
            options={'ordering': ['created_at']},
        ),
    ]
